### ISSUE TITLE
Reports on campaign for logged in user - wireframes

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#1]
Базирано на юзър сторитата
https://docs.google.com/spreadsheets/d/1WVxlDB7iF34-VVffUU4geKLbsT6HjtQhkjEBOLYfJJ8/edit#gid=0

**Comment by digitallymarked** [comment]
Work already done in the main Figma file https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?type=design&node-id=4662-14&mode=design&t=By3lhhwTyVF2xjUb-11
