### ISSUE TITLE
UI kit

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#10]
Имаме нужда от изграждането на UI kit за сайта.
Осигурен е темплейт, в който да се заменят конкретни елементи спрямо визуалната идентичност на Podkrepi.bg.
Трябва да се заменят всички шрифтове, цветове, форми на бутони (ползваме пълно закръгление), states и т.н.

1. Нашият brandbook (в процес на работа): https://drive.google.com/file/d/1aYIEm9dCwuHIm8sM6s-Ru-Lhr9c6wRYe/view
2. Уебсайт: https://podkrepi.bg
3. Файл във Figma с темплейта: https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=0%3A7243

Очакван краен продукт: Редакции директно във Figma файла

**Comment by digitallymarked** [comment]
We are moving towards a new organisation style in Figma. Closing this

**Comment by digitallymarked** [comment]
We are moving towards a new organisation style in Figma. Closing this
