### ISSUE TITLE
Скици при успешно извършено  плащане – thank you page т.е страница която индикира завършване на процеса на дарение. Аз си представям линк към други кампании и новини

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#11]

**Comment by digitallymarked** [comment]
@swolf86 this looks like it's already done in production. Can we close it?

**Comment by swolf86** [comment]
@digitallymarked thank you page done and still missing the customer satisfaction survey

**Comment by digitallymarked** [comment]
Ok, moving the survey to Trello and closing this
