### ISSUE TITLE
Отчет ПУЛС за ноември, декември 2022 г.

### ISSUE THREAD

**Issue by MariKaro** [podkrepi-bg/design#111]
Да се направи картинка, подходяща за фейсбук пост, с обобщените разходи по различните пера направени от фондация ПУЛС за периода на отчитане - ноември, декември 2022 г.

-  Медицински прегледи и манипулации - 881,31 лв.
 - Хранителни продукти - 568,3 лв.
- Облекло - 808 лв.
- Консултантски дейности, свързани с опазване правата на човека - 1000 лв.
- Други - 72,43 лв.
- Общо за периода: 3330,04 лв.
Моля да се проверят цифрите.
[https://docs.google.com/spreadsheets/d/1W6RcE4skXusEqoc6HNsMuJEwIvm_ouBB/edit#gid=1208886583](url)

**Comment by swolf86** [comment]
За неши това ли имаш предвид  да се направи @MariKaro https://www.facebook.com/podkrepi.bg/photos/pcb.460134389529606/460059496203762

**Comment by swolf86** [comment]
Радо, за тези данни говоря. И може да не са представени с графика, а като снимка и текст на нея

**Comment by swolf86** [comment]
Венете работи по това

**Comment by venetaradeva** [comment]
Привет, прилагам пълния набор странички, ако все пак решите да постнете "цел" и "какво предстои" (така или иначе трябваше да ги направя за шаблона, поне да не ги търсите)
-новото перо е "правни дейности"
-моля ако може преди да се постне някой да погледне цифрите на слайд 03 Какво е направено до момента , да знам, че правилно съм разбрала таблицата- Събрахме общо...от тези бяха ....   Благодаря :)
-ще ги кача в папка отчети на google drive, щом кажете, че всичко е наред с тях
Оставам на разположение при нужда от корекции


![01 FRONT COVER INTERIM REPORT CAMPAIGN FB FONDATION PULSE 11-12.22.jpg](https://images.zenhubusercontent.com/63d19190e420b7ce5eff5b0f/ae815861-44af-41a3-a46d-18d8bab56b7c)![02 MISSION INTERIM REPORT CAMPAIGN FB FONDATION PULSE.jpg](https://images.zenhubusercontent.com/63d19190e420b7ce5eff5b0f/647d814b-60fc-465b-8717-c49db521943d)![03 WHAT IS DONE INTERIM REPORT CAMPAIGN FB FONDATION PULSE 11-12.22.jpg](https://images.zenhubusercontent.com/63d19190e420b7ce5eff5b0f/fa7561a7-7a05-4867-a68c-ef580fd68a46)![04 WHAT IS DONE 2 NTERIM REPORT CAMPAIGN FB FONDATION PULSE 11-12.22.jpg](https://images.zenhubusercontent.com/63d19190e420b7ce5eff5b0f/cf390e8b-1011-4912-9d0c-00f2831775a4)![05 WHAT WILL BE DONE INTERIM REPORT CAMPAIGN FB FONDATION PULSE 11-12.22.jpg](https://images.zenhubusercontent.com/63d19190e420b7ce5eff5b0f/deecd896-6b46-45d5-972c-1e49d81842e4)![06 BACK COVER INTERIM REPORT CAMPAIGN FB FONDATION PULSE 11-12.22.jpg](https://images.zenhubusercontent.com/63d19190e420b7ce5eff5b0f/44453c7e-65de-4af2-99d1-8458197bffbb)

**Comment by MariKaro** [comment]
Здравей, Вени,
Трябва да се промени слайда с каква сума е събрана и каква е похарчена.
Прилагам скрийншоти.
*По време на отчета* *събраната сума* остава - 8248 лв., *преведени* са -
5591 лв., тези са същите. *IX.2022 - са изразходени* - 2693 лв. - , а
*XI-XII.2022
изразходени* - 3330 лв.
Не знам дали да не кажем, че към днешна дата има събрани - 10 106 лв.
Поздрави,
Марияна

+359888546899
www.podkrepi.bg <https://podkrepi.bg/>






На пн, 6.02.2023 г. в 2:36 ч. venetaradeva ***@***.***>
написа:

**Comment by venetaradeva** [comment]
@MariKaro Здравей, да, тази страница е най-важната,сега ще я оправим. 
Ако отчетът е за период ноември-декември ми се струва объркващо да включим суми и от януари. Бих препоръчала да не смесваме нещата, а евентуално да съобщим за добрия развой  на кампанията с отделен пост- хем като мотивация и добри новини, хем като стимулиране за достигане на оставащото. Но ако кажете, мога да напиша нещо подобно " към 02.2023 събрахме 10 106лв." но после трябва да продължим "към 12.22 бяха преведени..." , което ще постави ненужни въпроси в главата на четящия защо тогава не им преведем другите, какво чакаме, отдолу говорим за сепетември, после за ноември и декември, а общата сума е към февруари... като че ли да останем в рамките на обявения отчетен период, нищо че гу пускаме през февруари. Ако правилно разбирам написаното.

За жалост не виждам прикачения файл, не знам ако ми го пуснеш в ux канала? Не съм сигурна, че ъпдейта, който пускам сега е това, което си ми писала по-горе.

![updated 03 WHAT IS DONE INTERIM REPORT CAMPAIGN FB FONDATION PULSE 11-12.22.jpg](https://images.zenhubusercontent.com/63d19190e420b7ce5eff5b0f/3a35c6c6-cf5b-45b9-a7c2-8a6aae0ddc27)

**Comment by MariKaro** [comment]
Така е добре, Вени.
Дадох повече информация, за да решим какво оставаме.
Ще погледна другите цифри след малко, че не можах и ще пиша.

Поздрави,
Марияна

+359888546899
www.podkrepi.bg <https://podkrepi.bg/>






На пн, 6.02.2023 г. в 13:42 ч. venetaradeva ***@***.***>
написа:

**Comment by venetaradeva** [comment]
Супер, радвам се, оставам на разположение.

**Comment by MariKaro** [comment]
Мисля, че всичко е ок.
Благодаря, Вени!
Поздрави,
Марияна

+359888546899
www.podkrepi.bg <https://podkrepi.bg/>






На пн, 6.02.2023 г. в 14:36 ч. venetaradeva ***@***.***>
написа:

**Comment by venetaradeva** [comment]
супер, 
моля, Мариянка, радвам се, че помогнах :) 
Хубава седмица!

**Comment by MariKaro** [comment]
И аз благодаря!
Усмихнат ден!

Поздрави,
Марияна

+359888546899
www.podkrepi.bg <https://podkrepi.bg/>






На вт, 7.02.2023 г. в 3:36 ч. venetaradeva ***@***.***>
написа:
