### ISSUE TITLE
Финален отчет по кампанията на Татяна

### ISSUE THREAD

**Issue by MariKaro** [podkrepi-bg/design#116]
Моля да се направи финален отчет по кампанията на Татяна.
Има изпратени документи за записване, кампус, закупуване на учебни материали, самолетен билет и други такси.

- [https://podkrepi.bg/campaigns/tanya-kosmicheskoto-momiche-na-bulgariya-po-putya-kum-zvezdite](url)

- https://docs.google.com/document/d/1K740tj9toATt9kvJTJr7rYSntcHRw170RMuy2ZzozZE/edit?usp=share_link](url)

- [https://drive.google.com/drive/folders/1EAcs-xNUrKmZAzrjK6Tfvdkm_ohwGFQ9?usp=share_link](url)
Можем да сложим и линкове към самите документи- те са със заличени лични данни

**Comment by lianazafeiri** [comment]
https://www.canva.com/design/DAFajHmM1J4/ooZsIgE8yOR-k5rbd_umTQ/edit?utm_content=DAFajHmM1J4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
