### ISSUE TITLE
Финален отчет на кампанията на училището за незрящи деца - СУУНЗ гр. Варна

### ISSUE THREAD

**Issue by MariKaro** [podkrepi-bg/design#117]
Моля за финален отчет по кампанията на СУУНЗ гр. Варна - незрящите деца
Отчетът може да намерите тук:
- [https://docs.google.com/spreadsheets/d/1--lkvVxY5C5_CTDD-hteHPyCQjwdQfDE/edit?usp=sharing&ouid=109508278047921904754&rtpof=true&sd=true](url)

- в папката има снимки, ако са необходими: [https://drive.google.com/drive/folders/17ggeb-_hLlCPLus7P8RvVdizo1WhnICk](url)

**Comment by swolf86** [comment]
https://www.canva.com/design/DAFafoEi-ac/p38rPxEBay7xOp3bXGHpVA/edit?utm_content=DAFafoEi-ac&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
