### ISSUE TITLE
Финален отчет на кампанията на Гората.бг 

### ISSUE THREAD

**Issue by MariKaro** [podkrepi-bg/design#119]
Да се направи финален отчет на кампанията за наводнените карловски села с организатор Гората.бг.
Отчетът:

- [https://docs.google.com/spreadsheets/d/1WoRgVvsFaDc7xWaoMfL4XrOXPwOLeowa/edit?usp=sharing&ouid=109508278047921904754&rtpof=true&sd=true](url)
Папка с видеа и снимки, свързани с раздаването на ваучерите:

- [https://drive.google.com/drive/folders/1OfBvwtLvtF6Gaewb_IwLXBjaWab8a7I7](url)

**Comment by lianazafeiri** [comment]
https://www.canva.com/design/DAFaiNW3nxg/7uAUwAaR39smrUWHLEbo6w/edit?utm_content=DAFaiNW3nxg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
