### ISSUE TITLE
New stamps on completed campaign

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#133]

**Comment by swolf86** [comment]
![image.png](https://images.zenhubusercontent.com/61669dd88e934412dd2f5543/1f60e98f-95a4-4afb-9de1-3686cf765f01)![image.png](https://images.zenhubusercontent.com/61669dd88e934412dd2f5543/d197017f-14b6-4327-843b-3a20c5db83ca)

Can someone please look for more elegant solution on these stamps. It should be something indicating completed campaing but not so in your face. Please make a research and let's discuss solutions

**Comment by milenasp** [comment]
Hi Rado, will look into it.

**Comment by milenasp** [comment]
Hi Rado, 

I researched how other platforms visualise this. The summary is here: 
https://docs.google.com/document/d/1bxyrIHL2ZQut28uf3S9z9TqDhw5kq1onTsr4ELhnJok/edit?usp=sharing

I looked at the existing Wireframes in Figma and it seems that we used to have another , more discreet stamp. Let's discuss in the meeting.
