### ISSUE TITLE
Формуляр за посещение на Организатор на място.

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#27]
Идеята е да остане възможност за попълване в електронен формат преди да се принтира.
https://docs.google.com/document/d/15yKSYMnFKWWf7662R41TS9jjh1izrSyV1LiWz_JInP8/edit

 идеята е да се попълва в екип Кампании (вътрешно, не на сайта, под формата на електронен документ в Драйва) преди посещението. После се принтира и се отива със самия принтиран документ на място, където се допълва на ръка с химикалка. Смисълът да има дизайн е, че при посещението тези листове ще бъдат пред очите на Организатора. Но, както казах, изобщо не е с приоритет - когато/ ако имате време. 

Това, което си представям е примерно някаква цветна рамка или цветни хедър и футър + лого. Нищо по-сложно от това.

**Comment by marianacat** [comment]
Бланката е готова: **Бланка за посещение на място**

Първата част на документа, където е часта " За предварително попълване" е направена да може да се попълва на компютър и тогава да се разпечатва.

Втората част на документа "За попълване на място" - се попълва на ръка.



Предадено на Грациела.

Сложена е в драйв: https://drive.google.com/drive/u/0/folders/1dG3Etm971INk45yUB7EZ_CZyaanakFOR
