### ISSUE TITLE
Information Architecture да се обнови 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#28]
Information Architecture (sitemap) който трябва да се обнови 
https://drive.google.com/file/d/18hsh5X_6QY9LgAlu7q5qc10Vz2m1_FI_/view?usp=sharing
с новите страница от дев.подкрепи.бг и Маркетинг 
FAQ obshti usloviq i tn

**Comment by marianacat** [comment]
В същия документ съм отворила нова страница и съм копирала Information Architecture (sitemap), където и работя.
[https://app.diagrams.net/#G1vD03OHd62aVOs_c_1J7agofFe8qL3Llh](url)

@swolf86 
Не можах да намеря Маркетинг FAQ
