### ISSUE TITLE
Блог страница - съдържание

### ISSUE THREAD

**Issue by rkoleva93** [podkrepi-bg/design#36]
Привет, 

[ТУК](https://docs.google.com/document/d/1g2_1JBG54eA_o_bz5yIg6E2oig7-82x7/edit)

Можете да намерите текста за началната страница на блога. Използвайте го като правите  темата за самия блог (до колкото си спомням скоро я сменихме).  Сложила съм я и в ексела с документите, които са пуснати към вас. 

Като си я запазите, можете да си затворите таска направо и вече като стигнете до там да видим страницата

Поздрави, 
Ради

**Comment by swolf86** [comment]
redesign on the blog
