### ISSUE TITLE
Статистика за код - социални медии

### ISSUE THREAD

**Issue by rkoleva93** [podkrepi-bg/design#49]

**Comment by rkoleva93** [comment]
Имаме нужда от визии за социалните медии, които да използваме да разпространим малко статистика, която Илко ни сподели.
Можете да видите поста тук: https://docs.google.com/document/d/1OnYPOeVl86sRnpcdg2UwIyEjQAZSvxBM33McLLkNRBQ/edit 

Трябват ни за фейсбук, инстаграм, линкедин и сторита за фейсбук и инстаграм. 

Виждам го като някакъв компютър с бинарен код или някакъв код, който да е написан на него.

**Comment by rkoleva93** [comment]
Имаме нужда от визии за социалните медии, които да използваме да разпространим малко статистика, която Илко ни сподели.
Можете да видите поста тук: https://docs.google.com/document/d/1OnYPOeVl86sRnpcdg2UwIyEjQAZSvxBM33McLLkNRBQ/edit 

Трябват ни за фейсбук, инстаграм, линкедин и сторита за фейсбук и инстаграм. 

Виждам го като някакъв компютър с бинарен код или някакъв код, който да е написан на него.

**Comment by atomov93** [comment]
https://www.canva.com/design/DAE-4rmwee0/fa5iX_z-qAlH0INGvVuduw/edit?utm_content=DAE-4rmwee0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by rkoleva93** [comment]
Привет,

Малко цвят, ако има на втората страница мисля, че ще стане идеално. Може човечето да е жълто, а пък компютъра да е син или нещо такова.

**Comment by atomov93** [comment]
Ок
