### ISSUE TITLE
страница за форма за отчети

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#59]
- тук ще трябва да се избере най-доброто място където това ще стой на коя страница, кой ще го попълва как ще се стига до тази страница? https://docs.google.com/document/d/1aEhVqI6R07XXTLCldrjZ2PmPek8iW6tvfnvg3OoaTOE/edit

**Comment by swolf86** [comment]
da se управи  https://dev.podkrepi.bg/finance-report

**Comment by margarita-n211** [comment]
Направила съм това, като вариант за бутони за годишните отчети. Моля за мнение 
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=14163%3A40594

**Comment by swolf86** [comment]
Добавих коментари в фигма

**Comment by swolf86** [comment]
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=14460%3A41714&t=mugbOLSVQigPjrst-3

Да се праща Фронт Енд
