### ISSUE TITLE
Страница на етикети - 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#61]

**Comment by swolf86** [comment]
https://drive.google.com/drive/folders/1kgD6i7xcziDJL4wN1iTfKYKAUQ-CrUMQ

**Comment by marianacat** [comment]
![Inkedетикети_LI.jpg](https://images.zenhubusercontent.com/61704cb3e4bc3c3aa92444e8/7919bc86-24f0-4df8-ae42-ce2d9b91ff8d)Нека да разгледаме Dev средата.
Страницата за етикетите може да се нагласи като категория в FAQ
https://dev.podkrepi.bg/faq/common-questions

**Comment by digitallymarked** [comment]
Already implemented in production
