### ISSUE TITLE
Визии за старта на Подкрепи.бг

### ISSUE THREAD

**Issue by rkoleva93** [podkrepi-bg/design#63]
Привет, 

Ще имаме нужда от визии за социалните медии за старта на Подкрепи.бг. 
Ето текстовете: 

https://docs.google.com/document/d/1zirNEt33FSg5B8XzOIft8TBPvo3jzBCbTYm1S5scgrc/edit?usp=sharing

Идеята тук е, че когато сложим линковете към самите кампании няма да се визуализират, тъй като са 2 и ще бъде визуализиран само единия, което би дало видимост само на 1-ната кампания, а не трябва да ги делим.
Проблемът би се решил, ако имаме визия, която да отразява факта, че има официален старт с линкове към кампаниите. 

Поздрави, 
Ради

**Comment by rkoleva93** [comment]
Гайс, тук някакъв ъпдейт?

**Comment by rkoleva93** [comment]
Гайс, тук някакъв ъпдейт?

**Comment by marianacat** [comment]
https://images.zenhubusercontent.com/393660793/b8682f06-e086-4d25-8290-9dd23777fd58/4e25871d68998c6c.mp4

**Comment by atomov93** [comment]
irrelevant в момента
