### ISSUE TITLE
Промяна на графиката на начална - Как работи платформата 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#65]
Трябва да се промни графиката стъпка "кандидатствай за кампания" -  да стане "кампании одобрени от Подкрепи.бг" ще ни трябва нова икона 

![IMG_20220729_214530.jpg](https://images.zenhubusercontent.com/61669dd88e934412dd2f5543/a1380d38-3d21-4bf5-8432-d9df29f7ad44)

**Comment by marianacat** [comment]
ето предложение за смяна на текстовете

![image](https://user-images.githubusercontent.com/92619043/181913721-4af4d0b3-e52b-48ca-9406-b06babb78033.png)

**Comment by marianacat** [comment]
Обсъдена е на общата среща.
Направена е корекция и е изпратена за подмяна.
