### ISSUE TITLE
Редизайн на менютата на мобилен, да се помисли/уеднакви с това, коеот Мариянка направи и  в UI kita

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#67]

**Comment by swolf86** [comment]
ще ни трябват pone 2 - 3 wirefeame

**Comment by marianacat** [comment]
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=8281%3A24205

**Comment by marianacat** [comment]
![image](https://user-images.githubusercontent.com/92619043/187584308-95388c44-c161-40f0-820e-5a9dd3a26fe0.png)
