### ISSUE TITLE
Bigger picture Info graphic

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#7]
![Podkrepi_Org_Structure](https://user-images.githubusercontent.com/75036745/137035367-4c9a7bdd-cfb0-4612-b72b-742438166ded.png)

Да се направи в стила на Подкрепи.бг

**Comment by digitallymarked** [comment]
@swolf86 is this still in works or we can close it?

**Comment by swolf86** [comment]
Not done but Let's close and open if required

**Comment by digitallymarked** [comment]
Moving to Trello then
