### ISSUE TITLE
Кампания на ПараКидс

### ISSUE THREAD

**Issue by MariKaro** [podkrepi-bg/design#72]

**Comment by MariKaro** [comment]
Да се започне работа по оформяне на кампанията на ПараКидс. Материалите за нея, могат да се намерят на следващия линк : [https://drive.google.com/drive/folders/1OAxRPfxi3tyJsEu3-0jTD5Y2HSu9mzr4](url)

**Comment by MariKaro** [comment]
А това е черновата на кампанията : [https://podkrepi.bg/campaigns/da-izgradim-igrishe-za-petank-za-decata-s-uvrezhdaniya-i-da-im-dadem-ravni-vuzmozhnosti-za-sportuvane](url)

**Comment by digitallymarked** [comment]
Already published
