### ISSUE TITLE
Кампания на Центъра за деца с увреден слух "Яника"

### ISSUE THREAD

**Issue by MariKaro** [podkrepi-bg/design#78]
1. Документът за кампанията е [https://docs.google.com/document/d/1n4WwvDwbhaK-YOImlcbW_OPPmR1mKBNWdZi7MzdSISY/edit]
2. Снимки [-https://drive.google.com/drive/folders/1qFSENv9AEcXkKjEfvd9SNz92ypQYhJXb]
3. Ще се добави Гарант и видео, когато ги имаме налични

**Comment by swolf86** [comment]
https://podkrepi.bg/campaigns/da-pomognem-na-decata-s-uvreden-sluh-ot-centur-yanika-da-se-nauchat-da-chuvat
