### ISSUE TITLE
А/Б платформ тестове - да се сетне 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#79]

**Comment by swolf86** [comment]
Тест дали ще ни помогне 
т Google Optimize - https://optimize.withgoogle.com/
Иначе ние в момента имплементирмаме Split https://www.split.io/solutions/a-b-testing/
други фрии туулове може да работя

**Comment by atomov93** [comment]
https://app.maze.co/projects/115330503 това е проекта за Maze, с който можем да тестваме във Фигма.

**Comment by atomov93** [comment]
Имаме вързан optimize. Очакваме тага и пускаме тестове

**Comment by atomov93** [comment]
Тестове пуснати
