### ISSUE TITLE
Кампанията на Валерия Гърневска организирана от Плюшено мече

### ISSUE THREAD

**Issue by MariKaro** [podkrepi-bg/design#87]
- Да се оправи дизайна на текста на кампанията

- Да се оправят сложените снимки. Чакаме да се направи видео за кампанията

- Да се избере подходяща снимка за background

- Да се преработи снимката на екипа на Плюшено мече и се махне 2020 
[https://podkrepi.bg/campaigns/da-sbudnem-mechtata-na-valeriya-da-vleze-v-top-5-na-evropa-v-tenisa](url) - кампания
[https://drive.google.com/drive/folders/1HHb8WQs_r2ZxuVMPkcm8JfOYsGmr4apJ?usp=sharing](url) снимки

**Comment by marianacat** [comment]
Това 2020 ли трябва да се махне?

![image.png](https://images.zenhubusercontent.com/61704cb3e4bc3c3aa92444e8/21799adc-f2f6-4b4b-adf5-26bd9264eb61)
