### ISSUE TITLE
Relook the user registration as a company, donation as a company

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/design#91]

**Comment by swolf86** [comment]
![image.png](https://images.zenhubusercontent.com/61669dd88e934412dd2f5543/d19b9ab8-c7b9-4c31-9847-0af45a5b097f)

**Comment by vanjari** [comment]
![draft_reg_flow.PNG](https://images.zenhubusercontent.com/6368092ec1262ae4187c129a/843110f4-ef33-48dc-8060-bf55d331dd94)![new profile - ЮЛНЦ.png](https://images.zenhubusercontent.com/6368092ec1262ae4187c129a/a7659a0f-15b0-4c69-8459-e422646e4538)![new profile - ФЛ.png](https://images.zenhubusercontent.com/6368092ec1262ae4187c129a/c9144024-a3d8-40b5-880d-e86b0317461d)![email confirmation.png](https://images.zenhubusercontent.com/6368092ec1262ae4187c129a/496b7c8d-5afe-4195-b27b-03405d2d3852)![email confirmed.png](https://images.zenhubusercontent.com/6368092ec1262ae4187c129a/157932fb-3413-4e15-8b4c-a33c8c51bd8d)

**Comment by digitallymarked** [comment]
Already in production
